language: node_js
node_js:
  - "node"
  - "lts/*"
cache: npm
jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script: npm install
    - stage: test
      name: Unit Tests
      script: npm test
    - stage: coverage
      name: "Report Coverage"
      script: npm run coveralls
stages:
  - install
  - test
